### PR TITLE
Added Affix to interpreter

### PR DESCRIPTION
**Pull request by AR-234**
Needed the total number of affixes (mods) on an item for a craft.
Have added it to the interpreter, hope it is all well, never worked with this language before.

If I missed something please tell me and I will fix it

### CODE REVIEW

**Comment by AR-234** [comment]
Fixed the Range parsing Error

**Comment by doomeer** [comment]
Thanks for including my suggestion.

About the last commit: actually, `..` was correct in the parser. This is because `-` creates ambiguity with negative numbers. So if you want to implement this fix you can remove the last commit and you just have to replace `-` with `..` in the `pp_` function. You can also keep this MR's focus on affixes and just remove the last commit if you prefer.

**Comment by AR-234** [comment]
I now know what you mean with the bug, it was the other way around.
Reverted it. 

Something for an other pull, you are right we should keep it clean.

**Comment by doomeer** [comment]
Thanks! I'll fix the dash issue now.

**Pull request merged**
